# Generated by Django 4.0.2 on 2022-02-24 20:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_dos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='What_WE_DO',
            new_name='What_DO',
        ),
    ]
