# Generated by Django 4.0.2 on 2022-02-24 20:35

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('what_we_dos', '0002_rename_what_we_do_what_do'),
    ]

    operations = [
        migrations.RenameField(
            model_name='what_do',
            old_name='created_date',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='what_do',
            name='decription',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
