# Generated by Django 4.0.2 on 2022-02-25 13:22

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Clothes', 'Clothes'), ('Objects', 'Objects'), ('Sticker', 'Sticker'), ('Book', 'Book'), ('Poster', 'Poster')], max_length=100)),
                ('price', models.ImageField(upload_to='')),
                ('decription_product', ckeditor.fields.RichTextField()),
                ('photo_principal', models.ImageField(upload_to='photos/%Y/%m/%d/')),
                ('photo_principal_2', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_principal_3', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('photo_principal_4', models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
