# Generated by Django 4.0.2 on 2022-02-25 13:35

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='review',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('M', 'M'), ('S', 'S'), ('XL', 'XL'), ('XXL', 'XXL'), ('Child 11-13', 'Child 11-13'), ('Child 3-4', 'Child 3-4'), ('Child 5-6', 'Child 5-6'), ('Child 7-8', 'Child 7-8'), ('Child 9-10', 'Child 9-10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(),
        ),
    ]
