# Generated by Django 4.0.2 on 2022-02-25 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_quantity_product_rating_product_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sizes_for_clothes',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('M', 'M'), ('S', 'S'), ('XL', 'XL'), ('XXL', 'XXL'), ('Child 11-13', 'Child 11-13'), ('Child 3-4', 'Child 3-4'), ('Child 5-6', 'Child 5-6'), ('Child 7-8', 'Child 7-8'), ('Child 9-10', 'Child 9-10')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Clothes', 'Clothes'), ('Objects', 'Objects'), ('Sticker', 'Sticker'), ('Book', 'Book'), ('Poster', 'Poster')], max_length=100),
        ),
    ]
