# Generated by Django 4.0.2 on 2022-03-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_photo_principal_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='photo_principal',
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_principal_2',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_principal_3',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='photo_principal_4',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
