# Generated by Django 4.0.2 on 2022-03-02 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_product_photo_principal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo_principal',
            field=models.ImageField(blank=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
