# Generated by Django 4.0.2 on 2022-03-02 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_photo_principal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo_principal',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
